# Generated by Django 5.0 on 2024-01-25 11:47

import django.db.models.deletion
import lib.custom_id
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("housing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=lib.custom_id.custom_id,
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="title of the house"),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="listings",
                        verbose_name="main image",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="description of the property"),
                ),
                ("price", models.FloatField()),
                ("is_available", models.BooleanField(default=True)),
                ("is_sold", models.BooleanField(default=False)),
                ("is_negotiable", models.BooleanField(default=False)),
                ("slug", models.SlugField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propert_address",
                        to="housing.address",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="propert_address",
                        to="housing.category",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="property_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Properties",
            },
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=lib.custom_id.custom_id,
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="listings", verbose_name="image"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="property_images",
                        to="property.property",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "House Images",
            },
        ),
    ]
