# Generated by Django 5.0 on 2024-01-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='more_details',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='terms_and_condition',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
